core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .forms import LoginForm

app_name = 'core'
urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html',
         authentication_form=LoginForm), name='login')
]

dashboard/urls.py
from django.urls import path
from . import views
app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index')
]

firs_python_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.url'), name='items'),
    path('dashboard/', include('dashboard.urls'), name='dashboard'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.

dashboard/models.py
from django.db import models

# Create your models here.

item/models.py
from django.contrib.auth.models import User
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'

    def __str__(self) -> str:
        return self.name


class Item(models.Model):
    category = models.ForeignKey(
        Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(
        User, related_name='items', on_delete=models.CASCADE)
    created_at = models.DateField(auto_now_add=True),
    image = models.ImageField(upload_to='item_images', blank=True, null=True)

    def __str__(self) -> str:
        return self.name

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full p-2 rounded-md text-sm'
    }))

    email = forms.EmailField(widget=forms.TextInput(attrs={
        'placeholder': 'name@email.com',
        'class': 'w-full p-2 rounded-md text-sm'
    }))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'w-full p-2 rounded-md text-sm'
    }))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'w-full p-2 rounded-md text-sm'
    }))


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full p-2 rounded-md text-sm'
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'w-full p-2 rounded-md text-sm'
    }))

item/forms.py
from django import forms
from .models import Item
INPUT_CLASSES = 'w-full p-2 rounded-lg border'


class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category', 'name', 'description', 'price', 'image')
        widgets = {
            'category': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
        }


class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name', 'description', 'price', 'image', 'is_sold')
        widgets = {
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
        }

core/views.py
from django.shortcuts import render, redirect

# Create your views here.
from item.models import Item, Category
from .forms import SignupForm


def index(request):
    items = Item.objects.filter(is_sold=False)[0:6]
    categories = Category.objects.all()
    return render(request, 'core/index.html', {
        'categories': categories,
        'items': items
    })


def contact(request):
    return render(request, 'core/contact.html')


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/login')
    form = SignupForm
    return render(request, 'core/signup.html', {
        'form': form
    })


def login(request):
    return render(request, 'core/login.html')

dashboard/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from item.models import Item

app_name = 'dashboard'


@login_required
def index(request):
    items = Item.objects.filter(created_by=request.user)
    return render(request, 'dashboard/index.html', {
        'items': items
    })

item/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.db.models import Q

from .forms import NewItemForm, EditItemForm
from .models import Item, Category


def browse(request):
    query = request.GET.get('query', '')
    category_id = request.GET.get('category', 0)
    items = Item.objects.filter(is_sold=False)
    categories = Category.objects.all()

    if query:
        items = items.filter(Q(name__icontains=query) |
                             Q(description__contains=query))

    if category_id:
        items = items.filter(category_id=category_id)

    return render(request, 'item/browse.html', {
        'items': items,
        'query': query,
        'categories': categories,
        'category_id': int(category_id)
    })


def details(request, id):
    item = get_object_or_404(Item, pk=id)
    related_items = Item.objects.filter(
        category=item.category, is_sold=False).exclude(pk=id)[0:3]
    return render(request, 'item/details.html', {
        'item': item,
        'related_items': related_items
    })


@login_required
def newItem(request):
    if request.method == 'POST':
        form = NewItemForm(request.POST, request.FILES)
        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()
            return redirect('item:details', item.id)
    else:
        form = NewItemForm()
    return render(request, 'item/form.html', {
        'form': form
    })


@login_required
def delete(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    item.delete()

    return redirect('dashboard:index')


@login_required
def edit(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    if request.method == 'POST':
        form = EditItemForm(request.POST, request.FILES, instance=item)
        if form.is_valid():
            form.save()
            return redirect('item:details', item.id)
    else:
        form = EditItemForm(instance=item)
    return render(request, 'item/form.html', {
        'form': form,
        'title': 'Edit Item'
    })

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>
        {% block title%}{%endblock%}| First Django Project
    </title>
</head>

<body class="grid items-center">
    <header class="border-b border-gray-400 bg-gray-100">
        <nav class="flex justify-between items-center p-2 m-2 ">
            <h1 class="font-bold text-md text-gray-500">Django Project</h1>
            <div class="font-semibold text-gray-600 text-sm space-x-3">
                <!-- <a class="hover:text-yellow-500" href="#">New Item</a> -->
                <a class="hover:text-yellow-500" href="{% url 'item:browse' %}">Browse</a>

                {% if request.user.is_authenticated %}
                <a class="hover:text-yellow-500" href="{% url 'item:new-item' %}">New Item</a>
                <a href="{% url 'dashboard:index' %}"
                    class="p-2 bg-yellow-500 font-bold rounded-md hover:bg-yellow-700 hover:text-white">Dashboard</a>

                <!-- <a href="#" class="p-2 bg-blue-500 font-bold rounded-md hover:bg-blue-700 hover:text-white">Logout</a> -->
                {% else %}
                <a href="{% url 'core:signup' %}"
                    class="p-2 bg-yellow-500 font-bold rounded-md hover:bg-yellow-700 hover:text-white">Sign
                    Up</a>
                <a href="{% url 'core:login' %}"
                    class="p-2 bg-blue-500 font-bold rounded-md hover:bg-blue-700 hover:text-white">Login</a>
                {% endif %}
            </div>
        </nav>
    </header>
    <div class="flex items-center justify-center">
        {% block content %}

        {% endblock %}
    </div>
    <footer class="fixed w-full bottom-0 border-b bg-gray-400">
        <nav class="flex justify-between items-center p-1">
            <h1 class="text-sm text-white">@Django Arkrai</h1>
            <div class="text-white text-sm space-x-3">
                <a class="hover:text-yellow-500" href="/">Home</a>
                <a class="hover:text-yellow-500" href="{% url 'core:contact' %}">Contact Us</a>
                <a class="hover:text-yellow-500" href="#">About Us</a>
            </div>
            <div class="font-semibold text-gray-700 text-sm space-x-3">
                <span class="text-sm">Alright Reserve 2023</span>
            </div>
        </nav>
    </footer>
</body>

</html>

core/templates/core/contact.html
{% extends 'core/base.html' %}
{%block title%} Contact {%endblock%}
{% block content %}
<h1 class="text-3xl text-gray-500">
    This is Contact Page
</h1>
{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}
{%block title%} Welcome {%endblock%}
{% block content %}
<div class="grid grid-cols-4 gap-4 w-full h-full p-6">
    <!-- left -->
    <div class="col-span-1 bg-gray-100 rounded-lg">
        <h1 class="text-6xl ">Left</h1>
    </div>

    <!-- right -->
    <div class="col-span-3 bg-gray-200 rounded-lg mb-4">
        <div class="grid grid-cols-3 flex items-center justify-between gap-3 m-2">
            {% for item in items %}
            <a href="{% url 'item:details' item.id %}" class="col-span-1 bg-white p-1 w-full rounded-lg h-full max-h-68 flex flex-col justify-between
            drop-shadow-md">
                <header class="p-3">
                    <h3 class="font-bold text-md text-gray-600">{{ item.name }}</h3>
                    <span class="text-sm text-gray-500">${{ item.price }}</span>
                </header>
                <div class="p-3">
                    <img class="w-full object-cover min-h-50" src="{{ item.image.url }}" alt="">
                </div>
                <footer class="p-3">
                    <span class="float-right text-xs font-semibold bg-yellow-100 p-1 rounded-md">
                        {{ item.category.name}}</span>
                </footer>
            </a>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}


{% block title %}
Login
{% endblock %}


{% block content %}
<div class="w-1/4 bg-gray-100 my-6 mx-auto p-6 rounded-xl drop-shadow-md">
    <h1 class="text-xl font-bold text-gray-500 pb-1">Login</h1>
    <hr>
    <form action="." method="post" class="space-y-3 text-gray-500 text-sm">
        {% csrf_token %}
        <div>
            <label for="username" class="inline-block  ">Username</label><br>
            {{ form.username }}
        </div>
        <div>
            <label for="password1" class="inline-block  ">Password</label><br>
            {{ form.password }}
        </div>
        {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form.errors %}
            {{ field.errors }}
            {% endfor %}
            {{ form.non_field_errors }}
        </div>
        {% endif %}

        <button class="mt-4 hover:bg-blue-700 bg-blue-500 text-md font-semibold px-2 py-1 rounded-md text-white">
            Login
        </button>
    </form>
</div>
{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}
Sign Up
{% endblock %}


{% block content %}
<div class="w-1/4 bg-gray-100 my-6 mx-auto p-6 rounded-xl drop-shadow-md">
    <h1 class="text-xl font-bold text-gray-500 pb-1">Sign Up</h1>
    <hr>
    <form action="." method="post" class="space-y-3 text-gray-500 text-sm">
        {% csrf_token %}
        <div>
            <label for="username" class="inline-block ">Username</label><br>
            {{ form.username }}
        </div>
        <div>
            <label for="email" class="inline-block  ">Email</label><br>
            {{ form.email }}
        </div>
        <div>
            <label for="password1" class="inline-block  ">Password</label><br>
            {{ form.password1 }}
        </div>
        <div>
            <label for="password2" class="inline-block  ">Repeat Password</label><br>
            {{ form.password2 }}
        </div>
        {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form.errors %}
            {{ field.errors }}
            {% endfor %}
            {{ form.non_field_errors }}
        </div>
        {% endif %}

        <button class="mt-4 hover:bg-blue-700 bg-blue-500 text-md font-semibold px-2 py-1 rounded-md text-white">
            Submit
        </button>
    </form>
</div>
{% endblock %}

dashboard/templates/dashboard/index.html
{% extends 'core/base.html' %}
{%block title%} Dashboard {%endblock%}
{% block content %}
<div class="grid grid-cols-4 gap-4 w-full h-full p-6">
    <!-- left -->
    <div class="col-span-1 bg-gray-100 rounded-lg">
        <h1 class="text-6xl "></h1>
    </div>

    <!-- right -->
    <div class="col-span-3 bg-gray-200 rounded-lg mb-4">
        <div class="grid grid-cols-3 flex items-center justify-between gap-3 m-2">
            {% for item in items %}
            <a href="{% url 'item:details' item.id %}" class="col-span-1 bg-white p-1 w-full rounded-lg h-full max-h-68 flex flex-col justify-between
            drop-shadow-md">
                <header class="p-3">
                    <h3 class="font-bold text-md text-gray-600">{{ item.name }}</h3>
                    <span class="text-sm text-gray-500">${{ item.price }}</span>
                </header>
                <div class="p-3">
                    <img class="w-full object-cover min-h-50" src="{{ item.image.url }}" alt="">
                </div>
                <footer class="p-3">
                    <span class="float-right text-xs font-semibold bg-yellow-100 p-1 rounded-md">
                        {{ item.category.name}}</span>
                </footer>
            </a>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

item/templates/item/browse.html
{% extends 'core/base.html' %}

{% block title %}
Browse Items
{% endblock %}


{% block content %}
<div class="grid grid-cols-4 gap-4 w-full h-full p-6">
    <!-- left -->
    <div class="col-span-1 bg-gray-100 rounded-lg p-3">
        <form action="{% url 'item:browse' %}" method="get">
            <div class="flex items-center justify-between">
                <h3 class="text-md font-bold text-gray-600 pb-3">Filter</h3>
                {%if category_id or query%}
                <a href="{% url 'item:browse' %}"
                    class="text-xs px-2 py-1 bg-gray-200 rounded-md hover:bg-gray-400">Clear
                    Filter</a>
                {%endif%}
            </div>
            <div class="flex items-center">
                <input class="w-full py-2 px-3 border rounded-l-md text-xs" name="query" type="text"
                    value="{{ query }}">
                <button type="submit" class="px-3 py-2 rounded-r-md bg-yellow-200 text-xs">Search</button>
            </div>

            <hr class="my-6">
            <p class="text-md text-gray-500 font-semibold">Categories</p>
            <ul>

                {% for category in categories %}

                <a href="{% url 'item:browse' %}?query={{ query }}&category={{ category.id }}">
                    <li
                        class="text-sm text-gray-600 p-3 {% if category_id == category.id %} bg-gray-400 {% endif %} bg-gray-300 rounded-xl mt-1">
                        {{category.name }}
                    </li>
                </a>
                {% endfor %}

            </ul>
        </form>
    </div>

    <!-- right -->
    <div class="col-span-3 bg-gray-200 rounded-lg mb-4">
        <div class="grid grid-cols-3 flex items-center justify-between gap-3 m-2">
            {% for item in items %}
            <a href="{% url 'item:details' item.id %}" class="col-span-1 bg-white p-1 w-full rounded-lg h-full max-h-68 flex flex-col justify-between
            drop-shadow-md">
                <header class="p-3">
                    <h3 class="font-bold text-md text-gray-600">{{ item.name }}</h3>
                    <span class="text-sm text-gray-500">${{ item.price }}</span>
                </header>
                <div class="p-3">
                    <img class="w-full object-cover min-h-50" src="{{ item.image.url }}" alt="">
                </div>
                <footer class="p-3">
                    <span class="float-right text-xs font-semibold bg-yellow-100 p-1 rounded-md">
                        {{ item.category.name}}</span>
                </footer>
            </a>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

item/templates/item/details.html
{% extends 'core/base.html' %}
{%block title%} {{ item.name }} {%endblock%}


{% block content%}
<div class="grid grid-cols-2 p-5">
    <div class="col-span-1 p-5 grid grid-cols-1 gap-3">
        <div class="flex items-right justify-right">
            <img src="{{ item.image.url }}" alt="" class="rounded-xl max-h-96 min-h-50 h-96">
        </div>
        <span>You might like:</span>
        <div class="flex  items-center">
            {% for r in related_items %}
            <div class="p-2">
                <img src="{{ r.image.url }}" alt="" class="min-w-10 max-w-20 w-28 h-[50%]">
            </div>
            {% endfor %}

        </div>

    </div>
    <div class="col-span-1 flex flex-col justify-center">
        <div>
            <h1 class="text-xl font-semibold">{{ item.name }}</h1>
            <span>${{ item.price }}</span>
            <p class="text-justify mr-5 mt-3">{{ item.description }}</p>
        </div>
        {% if request.user.is_authenticated %}
        <div class="bg-gray-300 inline-block p-6 rounded-lg space-x-2">
            <a href="{% url 'item:delete' item.id %}" class="bg-red-500 px-2 py-1 rounded-md text-sm text-white">
                Delete
            </a>
            <a href="{% url 'item:edit' item.id %}" class="bg-green-500 px-2 py-1 rounded-md text-sm text-white">
                Edit
            </a>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

item/templates/item/form.html
{% extends 'core/base.html' %}

{% block title %}
New Iten
{% endblock %}

{% block content %}
<div class="w-1/2 bg-gray-100 my-6 mx-auto p-6 rounded-xl">
    <h1 class="text-md text-gray-600 font-semibold">New Item</h1>
    <form action="." method="post" enctype="multipart/form-data" class="space-y-3 text-gray-500 text-sm">
        {% csrf_token %}
        <div class="space-y-4">
            {{ form.as_p }}
        </div>
        {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form.errors %}
            {{ field.errors }}
            {% endfor %}
            {{ form.non_field_errors }}
        </div>
        {% endif %}

        <button class="mt-4 hover:bg-blue-700 bg-blue-500 text-md font-semibold px-2 py-1 rounded-md text-white">
            Save
        </button>
    </form>
</div>
{% endblock %}